version:'3'
services:
  mongodb:
    image:mongo
    ports:
      - 27017:27017
    environment:
      - USERNAME:root
      - PASSWORD:sdfsdf
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8080
    environment:
      - USERNAME:root
      - PASSWORD:sdfsdf